name: big_decimal_intl
description: Parsing and formatting of big decimal numbers.
version: 1.0.0
repository: https://github.com/t-unit/big_decimal_intl

environment:
  sdk: ">=3.6.0 <=4.0.0"

dependencies:
 big_decimal: ">=0.5.0"
 intl: ">=0.20.1"

dev_dependencies:
  lints: ^5.1.0
  test: ^1.24.0
